version: '3.2'

services:
    wordpress:
        image: wordpress:latest
        restart: always
        depends_on:
            - wordpressdb
        networks:
            - wordpress-network
        ports:
            - "8008:80"
        volumes:
            - ./wp-config/php.conf.uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
            - ./wp-app:/var/www/html
            - ./wp-themes/ohi-theme:/var/www/html/wp-content/themes/ohi-theme
            # - ./wp-themes/blankslate:/var/www/html/wp-content/themes/blankslate
            - ./wp-plugins/ohi-projects:/var/www/html/wp-content/plugins/ohi-projects
            - ./wp-plugins/ohi-trips:/var/www/html/wp-content/plugins/ohi-trips
            - ./wp-plugins/advanced-custom-fields-pro:/var/www/html/wp-content/plugins/advanced-custom-fields-pro
            - ./wp-plugins/gravityforms:/var/www/html/wp-content/plugins/gravityforms
            - ./wp-plugins/gravityformsuserregistration:/var/www/html/wp-content/plugins/gravityformsuserregistration
            # - ./wp-config/wp-config.php:/var/www/html/wp-config.php
        environment:
            WORDPRESS_DB_HOST: wordpressdb
            WORDPRESS_DB_NAME: wordpress
            WORDPRESS_DB_USER: wordpress
            WORDPRESS_DB_PASSWORD: wordpress
            
    wordpressdb:
        image: mysql:5.7
        volumes:
            - dbdata:/var/lib/mysql
        restart: always
        networks:
            - wordpress-network
        environment:
            MYSQL_ROOT_PASSWORD: wordpress
            MYSQL_DATABASE: wordpress
            MYSQL_USER: wordpress
            MYSQL_PASSWORD: wordpress
        ports:
            - 3308:3306
        volumes:
            - ./wp-data:/docker-entrypoint-initdb.d

networks:
    wordpress-network:
        driver: bridge