version: '3.2'

services:
    wordpress:
        image: wordpress:latest
        restart: always
        depends_on:
            - wordpressdb
        networks:
            - wordpress-network
        ports:
            - "8787:80"
        volumes:
            - ./wp-config/php.conf.uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
            - ./wp-app:/var/www/html
            # - ./wp-themes/<theme>:/var/www/html/wp-content/themes/<theme>
            # - ./wp-plugins/<plugin>:/var/www/html/wp-content/plugins/<plugin>
            # - ./wp-config/wp-config.php:/var/www/html/wp-config.php
        environment:
            WORDPRESS_DB_HOST: wordpressdb
            WORDPRESS_DB_NAME: wordpress
            WORDPRESS_DB_USER: wordpress
            WORDPRESS_DB_PASSWORD: wordpress
            
    wordpressdb:
        image: mysql:5.7
        volumes:
            - dbdata:/var/lib/mysql
        restart: always
        networks:
            - wordpress-network
        environment:
            MYSQL_ROOT_PASSWORD: wordpress
            MYSQL_DATABASE: wordpress
            MYSQL_USER: wordpress
            MYSQL_PASSWORD: wordpress
        ports:
            - 3307:3306
        volumes:
            - ./wp-data:/docker-entrypoint-initdb.d

networks:
    wordpress-network:
        driver: bridge